### ISSUE TITLE
Missing Network Charges 

### ISSUE THREAD

**Issue by DerekPerezInfigen** [TallyIt/Issues#3]
MIssing Network Charges-Sugar Australia 
To	Subject	Size	Sent	Categories	
Walter Wang	RE: May bills from Tally	171 KB	Wed 8:33 PM

**Comment by EwenStewartAtTally** [comment]
SOLARISP.A400 product has been added 
 select * from product.ProductItems where ProductName = 'SOLARISP.A400' 
 select * from finance.AccountProduct where AccountId = 19 
 select * from finance.Accounts where id=19

**Comment by EwenStewartAtTally** [comment]
Setup looks good

**Comment by WalterAtTally** [comment]
@EwenStewartAtTally, Jemena (SOLARIS) rates is missing

**Comment by EwenStewartAtTally** [comment]
Loaded the rates for solaris
