### ISSUE TITLE
When creating Market market.AncillaryServiceCharge  - we MUST Write the DELTA between versions - not the new total 

### ISSUE THREAD

**Issue by EwenStewartAtTally** [TallyIt/Issues#36]
![image](https://user-images.githubusercontent.com/45586744/60234004-e6493180-98e5-11e9-8c10-20aeafb14853.png)

**Comment by WalterAtTally** [comment]
The current stored values ARE the delta.
![image](https://user-images.githubusercontent.com/48546325/60316895-f75e7500-99af-11e9-8203-e28cb4fc50a9.png)
