### ISSUE TITLE
NMI 024 and 025 showing duplicate metering charge lines

### ISSUE THREAD

**Issue by WalterAtTally** [TallyIt/Issues#40]
Duplicate line items:
SAPN Type1-4 Metering Charge   $60.22
Metering Charge  $60.22

**Comment by WalterAtTally** [comment]
This is caused by duplicate product items
one from UMPLP.VZSN024	UMPLP.VZSN024.METER14
one from INFIGEN.METER.SITESPECIFIC

@EwenStewartAtTally which one should be removed?

**Comment by DerekPerezInfigen** [comment]
[BBPEM (Infigen) LNSP ENERGYAP_April_SO_1574135_210-000405.pdf](https://github.com/TallyIt/Issues/files/3341666/BBPEM.Infigen.LNSP.ENERGYAP_April_SO_1574135_210-000405.pdf)

There is no charge in Plus ES for NMI 24/25 for the Plus ES metering charge( see attached) . So it should only be one 60.22 which is the related to SAPN Type1-4 Metering Charge.

**Comment by EwenStewartAtTally** [comment]
Fixed - porduct updated - but mainly excluded non EBKQ interval channels in the data reader
