### ISSUE TITLE
Intervention Cost: Denominator to use to calculate the rate per Kwh

### ISSUE THREAD

**Issue by DerekPerezInfigen** [TallyIt/Issues#46]
Just on intervention, numerator to calculate intervention should be REGIONAL_CUSTOMER_ENERGY only not the total totalMarketEnergyKwh

**Comment by EwenStewartAtTally** [comment]
Chase up with Victor 
We are using REGIONAL_CUSTOMER_ENERGY 
but semm to be being passed the wrong values
