### ISSUE TITLE
All NMIs: Meter Data Agency Web graphs for Infomet   Web Graphs Energy Awareness Pack   Metering Co-Ordinator

### ISSUE THREAD

**Issue by DerekPerezInfigen** [TallyIt/Issues#47]
I am just reconciling the following vs the per cost based on the invoice attached. Looks a bit off in terms of per day charge.

Meter Data Agency
Web graphs for Infomet  
Web Graphs Energy Awareness Pack   Metering Co-Ordinator

Example: NMI 461 charges are as follows:

0.9495 $/Day  
0.3613 $/Day
0.3337 $/Day

When i recalculate based on the Plus ES invoice, I am getting slightly different amount:

374/365*10/11( pre GST)= 0.9315 per day
143/365*10/11( pre-GST)= 0.3561 per day
132/365*10/11(pre-GST)=0.3287 per day

[BBPEM.pdf](https://github.com/TallyIt/Issues/files/3348519/BBPEM.pdf)

**Comment by EwenStewartAtTally** [comment]
updated rates in production
