### ISSUE TITLE
NMI SAAAAB460 Adelaide Brighton

### ISSUE THREAD

**Issue by DerekPerezInfigen** [TallyIt/Issues#48]
Supply charge rate doesnot look right. It is not 10.9166/day but 10.8807

NOUS volume charge is not 0.0442 but 0.042

**Comment by EwenStewartAtTally** [comment]
We believe it is correct

**Comment by DerekPerezInfigen** [comment]
I checked with SAPN now the rates should be 10.8807 and  0.042 and the NMI SAAAAB460 is classified as LVI
![image](https://user-images.githubusercontent.com/52262738/60563417-22293e80-9d9f-11e9-91a0-ac01aeab6067.png)

**Comment by EwenStewartAtTally** [comment]
Ok - Changed to LV   
![image](https://user-images.githubusercontent.com/45586744/60566922-c1ecc980-9dab-11e9-8460-6013e9a3f77f.png)

![image](https://user-images.githubusercontent.com/45586744/60566931-ce712200-9dab-11e9-8942-60a762b7d914.png)
