### ISSUE TITLE
Can we format the ABN the standard way e.g. 82 081 245 169 instead of without any spaces. Makes it easier to visually see if we are missing any numbers

### ISSUE THREAD

**Issue by IFNClu** [TallyIt/Issues#53]

**Comment by EwenStewartAtTally** [comment]
Sunny/Walter - can we please format this.  I've change the DB to support 50 chars - but we should remove all spaces from the passed text then reformat in the rendering page  - eg write a function that takes a string and returns the formatted ABN - THis means we dont rely on how the ABN is stored  ( it should be stored without spaces )

**Comment by WalterAtTally** [comment]
Fixed invoice template to display Abn/Acn in the desired format
@sunny-at-tally , can you check why the Abn/Acn field is not visible in CRM? and why is it stored with spaces in the database? e.g. Ramsey Health
https://test-infigenenergy.crm6.dynamics.com/main.aspx?appid=e83c20e0-9c4a-e911-a844-000d3a6a4119&pagetype=entityrecord&etn=account&id=a597aa89-d097-e911-a856-000d3a6a4fa1

**Comment by sunny-at-tally** [comment]
It will show when y change Account Type = C&I.

**Comment by WalterAtTally** [comment]
@EwenStewartAtTally , did you update the replication trigger to strip the spaces?

**Comment by EwenStewartAtTally** [comment]
@WalterAtTally  Yes - replication removes the space  - plus DB fields has been increased
